package org.nucleus8583.core.config;

import org.nucleus8583.core.MessageSerializer;

import java.util.Map;

@Order(Order.FIRST + 1)
public class Codec8583SerializerConfig implements Configurer {

    @Override
    public void configure(Configuration config) {
        config.define("codec8583", MessageSerializer.custom(config)
                .defineField(0, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(1, "bitmap")
                .defineField(2, "ans ..")
                .defineField(3, "ans", Map.of("length", "6", "alignment", "none"))
                .defineField(4, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(5, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(6, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(7, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(8, "ans", Map.of("length", "8", "alignment", "none"))
                .defineField(9, "ans", Map.of("length", "8", "alignment", "none"))
                .defineField(10, "ans", Map.of("length", "8", "alignment", "none"))
                .defineField(11, "ans", Map.of("length", "6", "alignment", "none"))
                .defineField(12, "ans", Map.of("length", "6", "alignment", "none"))
                .defineField(13, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(14, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(15, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(16, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(17, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(18, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(19, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(20, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(21, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(22, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(23, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(24, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(25, "ans", Map.of("length", "2", "alignment", "none"))
                .defineField(26, "ans", Map.of("length", "2", "alignment", "none"))
                .defineField(27, "ans", Map.of("length", "1", "alignment", "none"))
                .defineField(28, "ans", Map.of("length", "9", "alignment", "none"))
                .defineField(29, "ans", Map.of("length", "9", "alignment", "none"))
                .defineField(30, "ans", Map.of("length", "9", "alignment", "none"))
                .defineField(31, "ans", Map.of("length", "9", "alignment", "none"))
                .defineField(32, "ans ..")
                .defineField(33, "ans ..")
                .defineField(34, "ans ..")
                .defineField(35, "ans ..")
                .defineField(36, "ans ...")
                .defineField(37, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(38, "ans", Map.of("length", "6", "alignment", "none"))
                .defineField(39, "ans", Map.of("length", "2", "alignment", "none"))
                .defineField(40, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(41, "ans", Map.of("length", "8", "alignment", "none"))
                .defineField(42, "ans", Map.of("length", "15", "alignment", "none"))
                .defineField(43, "ans", Map.of("length", "40", "alignment", "none"))
                .defineField(44, "ans ..")
                .defineField(45, "ans ..")
                .defineField(46, "ans ...")
                .defineField(47, "ans ...")
                .defineField(48, "ans ...")
                .defineField(49, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(50, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(51, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(52, "ans", Map.of("length", "16", "alignment", "none"))
                .defineField(53, "ans", Map.of("length", "16", "alignment", "none"))
                .defineField(54, "ans ...")
                .defineField(55, "ans ...")
                .defineField(56, "ans ...")
                .defineField(57, "ans ...")
                .defineField(58, "ans ...")
                .defineField(59, "ans ...")
                .defineField(60, "ans ...")
                .defineField(61, "ans ...")
                .defineField(62, "ans ...")
                .defineField(63, "ans ...")
                .defineField(64, "b", Map.of("length", "16"))
                .defineField(65, "bitmap")
		        .defineField(66, "ans", Map.of("length", "1", "alignment", "none"))
                .defineField(67, "ans", Map.of("length", "2", "alignment", "none"))
                .defineField(68, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(69, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(70, "ans", Map.of("length", "3", "alignment", "none"))
                .defineField(71, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(72, "ans", Map.of("length", "4", "alignment", "none"))
                .defineField(73, "ans", Map.of("length", "6", "alignment", "none"))
                .defineField(74, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(75, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(76, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(77, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(78, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(79, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(80, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(81, "ans", Map.of("length", "10", "alignment", "none"))
                .defineField(82, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(83, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(84, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(85, "ans", Map.of("length", "12", "alignment", "none"))
                .defineField(86, "ans", Map.of("length", "16", "alignment", "none"))
                .defineField(87, "ans", Map.of("length", "16", "alignment", "none"))
                .defineField(88, "ans", Map.of("length", "16", "alignment", "none"))
                .defineField(89, "ans", Map.of("length", "16", "alignment", "none"))
                .defineField(90, "ans", Map.of("length", "26", "alignment", "none"))
                .defineField(91, "ans", Map.of("length", "1", "alignment", "none"))
                .defineField(92, "ans", Map.of("length", "2", "alignment", "none"))
                .defineField(93, "ans", Map.of("length", "6", "alignment", "none"))
                .defineField(94, "ans", Map.of("length", "7", "alignment", "none"))
                .defineField(95, "ans", Map.of("length", "42", "alignment", "none"))
                .defineField(96, "b", Map.of("length", "16"))
                .defineField(97, "ans", Map.of("length", "17", "alignment", "none"))
                .defineField(98, "ans", Map.of("length", "25", "alignment", "none"))
                .defineField(99, "ans ..")
                .defineField(100, "ans ..")
                .defineField(101, "ans ..")
                .defineField(102, "ans ..")
                .defineField(103, "ans ..")
                .defineField(104, "ans ...")
                .defineField(105, "ans ...")
                .defineField(106, "ans ...")
                .defineField(107, "ans ...")
                .defineField(108, "ans ...")
                .defineField(109, "ans ...")
                .defineField(110, "ans ...")
                .defineField(111, "ans ...")
                .defineField(112, "ans ...")
                .defineField(113, "ans ...")
                .defineField(114, "ans ...")
                .defineField(115, "ans ...")
                .defineField(116, "ans ...")
                .defineField(117, "ans ...")
                .defineField(118, "ans ...")
                .defineField(119, "ans ...")
                .defineField(120, "ans ...")
                .defineField(121, "ans ...")
                .defineField(122, "ans ...")
                .defineField(123, "ans ...")
                .defineField(124, "ans ...")
                .defineField(125, "ans ...")
                .defineField(126, "ans ...")
                .defineField(127, "ans ...")
                .defineField(128, "b", Map.of("length", "8"))
                .build());
    }
}
