package org.nucleus8583.core.config;

import org.nucleus8583.core.MessageSerializer;

import java.util.Map;

public class Codec8583No28SerializerConfig implements Configurer {

    @Override
    public void configure(Configuration config) {
        config.define("codec8583-no28", MessageSerializer.custom(config)
                .defineField(0, "n", Map.of("length", "4"))
                .defineField(1, "bitmap")
                .defineField(2, "n ..", Map.of("max-length", "16"))
                .defineField(3, "n", Map.of("length", "6"))
                .defineField(4, "n", Map.of("length", "12"))
                .defineField(5, "n", Map.of("length", "12"))
                .defineField(6, "n", Map.of("length", "12"))
                .defineField(7, "n", Map.of("length", "10"))
                .defineField(8, "n", Map.of("length", "8"))
                .defineField(9, "n", Map.of("length", "8"))
                .defineField(10, "n", Map.of("length", "8"))
                .defineField(11, "n", Map.of("length", "6"))
                .defineField(12, "n", Map.of("length", "6"))
                .defineField(13, "n", Map.of("length", "4"))
                .defineField(14, "n", Map.of("length", "4"))
                .defineField(15, "n", Map.of("length", "4"))
                .defineField(16, "n", Map.of("length", "4"))
                .defineField(17, "n", Map.of("length", "4"))
                .defineField(18, "n", Map.of("length", "4"))
                .defineField(19, "n", Map.of("length", "3"))
                .defineField(20, "n", Map.of("length", "3"))
                .defineField(21, "n", Map.of("length", "3"))
                .defineField(22, "n", Map.of("length", "3"))
                .defineField(23, "n", Map.of("length", "3"))
                .defineField(24, "n", Map.of("length", "3"))
                .defineField(25, "n", Map.of("length", "2"))
                .defineField(26, "n", Map.of("length", "2"))
                .defineField(27, "n", Map.of("length", "1"))
                .defineField(29, "s", Map.of("length", "9"))
                .defineField(32, "n ..", Map.of("max-length", "11"))
                .defineField(33, "n ..", Map.of("max-length", "11"))
                .defineField(34, "ans ..", Map.of("max-length", "28"))
                .defineField(35, "n ..", Map.of("max-length", "37"))
                .defineField(36, "ans ...", Map.of("max-length", "104"))
                .defineField(37, "s", Map.of("length", "12"))
                .defineField(38, "s", Map.of("length", "6"))
                .defineField(39, "s", Map.of("length", "2"))
                .defineField(40, "s", Map.of("length", "3"))
                .defineField(41, "s", Map.of("length", "8"))
                .defineField(42, "s", Map.of("length", "15"))
                .defineField(43, "s", Map.of("length", "40"))
                .defineField(44, "ans ..", Map.of("max-length", "25"))
                .defineField(45, "ans ..", Map.of("max-length", "76"))
                .defineField(46, "ans ...", Map.of("max-length", "999"))
                .defineField(47, "ans ...", Map.of("max-length", "999"))
                .defineField(48, "ans ...", Map.of("max-length", "999"))
                .defineField(49, "s", Map.of("length", "3"))
                .defineField(50, "s", Map.of("length", "3"))
                .defineField(51, "s", Map.of("length", "3"))
                .defineField(52, "n", Map.of("length", "16"))
                .defineField(53, "n", Map.of("length", "16"))
                .defineField(54, "ans ...", Map.of("max-length", "120"))
                .defineField(55, "ans ...", Map.of("max-length", "999"))
                .defineField(56, "ans ...", Map.of("max-length", "999"))
                .defineField(57, "ans ...", Map.of("max-length", "999"))
                .defineField(58, "ans ...", Map.of("max-length", "999"))
                .defineField(59, "ans ...", Map.of("max-length", "999"))
                .defineField(60, "ans ...", Map.of("max-length", "999"))
                .defineField(61, "ans ...", Map.of("max-length", "999"))
                .defineField(62, "ans ...", Map.of("max-length", "999"))
                .defineField(63, "ans ...", Map.of("max-length", "999"))
                .defineField(64, "b", Map.of("length", "8"))
                .defineField(65, "bitmap")
                .defineField(66, "n", Map.of("length", "1"))
                .defineField(67, "n", Map.of("length", "2"))
                .defineField(68, "n", Map.of("length", "3"))
                .defineField(69, "n", Map.of("length", "3"))
                .defineField(70, "n", Map.of("length", "3"))
                .defineField(71, "n", Map.of("length", "4"))
                .defineField(72, "n", Map.of("length", "4"))
                .defineField(73, "n", Map.of("length", "6"))
                .defineField(74, "n", Map.of("length", "10"))
                .defineField(75, "n", Map.of("length", "10"))
                .defineField(76, "n", Map.of("length", "10"))
                .defineField(77, "n", Map.of("length", "10"))
                .defineField(78, "n", Map.of("length", "10"))
                .defineField(79, "n", Map.of("length", "10"))
                .defineField(80, "n", Map.of("length", "10"))
                .defineField(81, "n", Map.of("length", "10"))
                .defineField(82, "n", Map.of("length", "12"))
                .defineField(83, "n", Map.of("length", "12"))
                .defineField(84, "n", Map.of("length", "12"))
                .defineField(85, "n", Map.of("length", "12"))
                .defineField(86, "n", Map.of("length", "16"))
                .defineField(87, "n", Map.of("length", "16"))
                .defineField(88, "n", Map.of("length", "16"))
                .defineField(89, "n", Map.of("length", "16"))
                .defineField(90, "n", Map.of("length", "42"))
                .defineField(91, "s", Map.of("length", "1"))
                .defineField(92, "s", Map.of("length", "2"))
                .defineField(93, "s", Map.of("length", "6"))
                .defineField(94, "s", Map.of("length", "7"))
                .defineField(95, "s", Map.of("length", "42"))
                .defineField(96, "b", Map.of("length", "16"))
                .defineField(98, "s", Map.of("length", "25"))
                .defineField(99, "n ..", Map.of("max-length", "11"))
                .defineField(100, "n ..", Map.of("max-length", "11"))
                .defineField(101, "ans ..", Map.of("max-length", "17"))
                .defineField(102, "ans ..", Map.of("max-length", "13"))
                .defineField(103, "ans ..", Map.of("max-length", "10"))
                .defineField(104, "ans ...", Map.of("max-length", "100"))
                .defineField(105, "ans ...", Map.of("max-length", "999"))
                .defineField(106, "ans ...", Map.of("max-length", "999"))
                .defineField(107, "ans ...", Map.of("max-length", "999"))
                .defineField(108, "ans ...", Map.of("max-length", "999"))
                .defineField(109, "ans ...", Map.of("max-length", "999"))
                .defineField(110, "ans ...", Map.of("max-length", "999"))
                .defineField(111, "ans ...", Map.of("max-length", "999"))
                .defineField(112, "ans ...", Map.of("max-length", "999"))
                .defineField(113, "ans ...", Map.of("max-length", "999"))
                .defineField(114, "ans ...", Map.of("max-length", "999"))
                .defineField(115, "ans ...", Map.of("max-length", "999"))
                .defineField(116, "ans ...", Map.of("max-length", "999"))
                .defineField(117, "ans ...", Map.of("max-length", "999"))
                .defineField(118, "ans ...", Map.of("max-length", "999"))
                .defineField(119, "ans ...", Map.of("max-length", "999"))
                .defineField(120, "ans ...", Map.of("max-length", "999"))
                .defineField(121, "ans ...", Map.of("max-length", "999"))
                .defineField(122, "ans ...", Map.of("max-length", "999"))
                .defineField(123, "ans ...", Map.of("max-length", "999"))
                .defineField(124, "ans ...", Map.of("max-length", "999"))
                .defineField(125, "ans ...", Map.of("max-length", "999"))
                .defineField(126, "ans ...", Map.of("max-length", "999"))
                .defineField(127, "ans ...", Map.of("max-length", "999"))
                .defineField(128, "b", Map.of("length", "8"))
                .build());
    }
}
