package org.nucleus8583.core.config;

import org.nucleus8583.core.MessageSerializer;

import java.util.Map;

@Order(Order.FIRST + 1)
public class Sys1SerializerConfig implements Configurer {

    @Override
    public void configure(Configuration config) {
        config.define("sys1", MessageSerializer.custom(config)
                .defineField(0, "an", Map.of("description", "MESSAGE TYPE INDICATOR", "length", "4"))
                .defineField(1, "bitmap", Map.of("description", "BITMAP"))
                .defineField(2, "n ..", Map.of("description", "PAN - PRIMARY ACCOUNT NUMBER", "max-length", "16"))
                .defineField(3, "n", Map.of("description", "PROCESSING CODE", "length", "6"))
                .defineField(4, "n", Map.of("description", "AMOUNT, TRANSACTION", "length", "12"))
                .defineField(5, "n", Map.of("description", "AMOUNT, SETTLEMENT", "length", "12"))
                .defineField(6, "n", Map.of("description", "AMOUNT, CARDHOLDER BILLING", "length", "12"))
                .defineField(7, "n", Map.of("description", "TRANSMISSION DATE AND TIME", "length", "10"))
                .defineField(8, "n", Map.of("description", "AMOUNT, CARDHOLDER BILLING FEE", "length", "8"))
                .defineField(9, "n", Map.of("description", "CONVERSION RATE, SETTLEMENT", "length", "8"))
                .defineField(10, "n", Map.of("description", "CONVERSION RATE, CARDHOLDER BILLING", "length", "8"))
                .defineField(11, "n", Map.of("description", "SYSTEM TRACE AUDIT NUMBER", "length", "6"))
                .defineField(12, "an", Map.of("description", "TIME, LOCAL TRANSACTION", "length", "6"))
                .defineField(13, "an", Map.of("description", "DATE, LOCAL TRANSACTION", "length", "4"))
                .defineField(14, "an", Map.of("description", "DATE, EXPIRATION", "length", "4"))
                .defineField(15, "an", Map.of("description", "DATE, SETTLEMENT", "length", "4"))
                .defineField(16, "an", Map.of("description", "DATE, CONVERSION", "length", "4"))
                .defineField(17, "an", Map.of("description", "DATE, CAPTURE", "length", "4"))
                .defineField(18, "an", Map.of("description", "MERCHANTS TYPE", "length", "4"))
                .defineField(19, "n", Map.of("description", "ACQUIRING INSTITUTION COUNTRY CODE", "length", "3"))
                .defineField(20, "n", Map.of("description", "PAN EXTENDED COUNTRY CODE", "length", "3"))
                .defineField(21, "n", Map.of("description", "FORWARDING INSTITUTION COUNTRY CODE", "length", "3"))
                .defineField(22, "n", Map.of("description", "POINT OF SERVICE ENTRY MODE", "length", "3"))
                .defineField(23, "n", Map.of("description", "CARD SEQUENCE NUMBER", "length", "3"))
                .defineField(24, "n", Map.of("description", "NETWORK INTERNATIONAL IDENTIFIEER", "length", "3"))
                .defineField(25, "n", Map.of("description", "POINT OF SERVICE CONDITION CODE", "length", "2"))
                .defineField(26, "n", Map.of("description", "POINT OF SERVICE PIN CAPTURE CODE", "length", "2"))
                .defineField(27, "n", Map.of("description", "AUTHORIZATION IDENTIFICATION RESP LEN", "length", "1"))
                .defineField(28, "n", Map.of("description", "AMOUNT, TRANSACTION FEE", "length", "9"))
                .defineField(29, "s", Map.of("description", "AMOUNT, SETTLEMENT FEE", "length", "9"))
                .defineField(30, "n", Map.of("description", "AMOUNT, TRANSACTION PROCESSING FEE", "length", "9"))
                .defineField(31, "n", Map.of("description", "AMOUNT, SETTLEMENT PROCESSING FEE", "length", "9"))
                .defineField(32, "n ..", Map.of("description", "ACQUIRING INSTITUTION IDENT CODE", "max-length", "11"))
                .defineField(33, "n ..", Map.of("description", "FORWARDING INSTITUTION IDENT CODE", "max-length", "11"))
                .defineField(34, "ans ..", Map.of("description", "PAN EXTENDED", "max-length", "28"))
                .defineField(35, "n ..", Map.of("description", "TRACK 2 DATA", "max-length", "37"))
                .defineField(36, "ans ...", Map.of("description", "TRACK 3 DATA", "max-length", "104"))
                .defineField(37, "s", Map.of("description", "RETRIEVAL REFERENCE NUMBER", "length", "12"))
                .defineField(38, "s", Map.of("description", "AUTHORIZATION IDENTIFICATION RESPONSE", "length", "6"))
                .defineField(39, "s", Map.of("description", "RESPONSE CODE", "length", "2"))
                .defineField(40, "s", Map.of("description", "SERVICE RESTRICTION CODE", "length", "3"))
                .defineField(41, "s", Map.of("description", "CARD ACCEPTOR TERMINAL IDENTIFICACION", "length", "8"))
                .defineField(42, "s", Map.of("description", "CARD ACCEPTOR IDENTIFICATION CODE", "length", "15"))
                .defineField(43, "s", Map.of("description", "CARD ACCEPTOR NAME/LOCATION", "length", "40"))
                .defineField(44, "ans ..", Map.of("description", "ADITIONAL RESPONSE DATA", "max-length", "25"))
                .defineField(45, "ans ..", Map.of("description", "TRACK 1 DATA", "max-length", "76"))
                .defineField(46, "ans ...", Map.of("description", "ADITIONAL DATA - ISO"))
                .defineField(47, "ans ...", Map.of("description", "ADITIONAL DATA - NATIONAL"))
                .defineField(48, "ans ...", Map.of("description", "ADITIONAL DATA - PRIVATE"))
                .defineField(49, "s", Map.of("description", "CURRENCY CODE, TRANSACTION", "length", "3"))
                .defineField(50, "s", Map.of("description", "CURRENCY CODE, SETTLEMENT", "length", "3"))
                .defineField(51, "s", Map.of("description", "CURRENCY CODE, CARDHOLDER BILLING", "length", "3"))
                .defineField(52, "n", Map.of("description", "PIN DATA", "length", "16"))
                .defineField(53, "n", Map.of("description", "SECURITY RELATED CONTROL INFORMATION", "length", "16"))
                .defineField(54, "ans ...", Map.of("description", "ADDITIONAL AMOUNTS", "max-length", "120"))
                .defineField(55, "ans ...", Map.of("description", "RESERVED ISO"))
                .defineField(56, "ans ...", Map.of("description", "RESERVED ISO"))
                .defineField(57, "ans ...", Map.of("description", "RESERVED NATIONAL"))
                .defineField(58, "ans ...", Map.of("description", "RESERVED NATIONAL"))
                .defineField(59, "ans ...", Map.of("description", "RESERVED NATIONAL"))
                .defineField(60, "ans ...", Map.of("description", "RESERVED PRIVATE"))
                .defineField(61, "ans ...", Map.of("description", "RESERVED PRIVATE"))
                .defineField(62, "ans ...", Map.of("description", "RESERVED PRIVATE"))
                .defineField(63, "ans ...", Map.of("description", "RESERVED PRIVATE"))
                .defineField(64, "b", Map.of("description", "MESSAGE AUTHENTICATION CODE FIELD", "length", "8"))
                .defineField(65, "bitmap", Map.of("description", "BITMAP, EXTENDED"))
                .defineField(66, "n", Map.of("description", "SETTLEMENT CODE", "length", "1"))
                .defineField(67, "n", Map.of("description", "EXTENDED PAYMENT CODE", "length", "2"))
                .defineField(68, "n", Map.of("description", "RECEIVING INSTITUTION COUNTRY CODE", "length", "3"))
                .defineField(69, "n", Map.of("description", "SETTLEMENT INSTITUTION COUNTRY CODE", "length", "3"))
                .defineField(70, "an", Map.of("description", "NETWORK MANAGEMENT INFORMATION CODE", "length", "3"))
                .defineField(71, "n", Map.of("description", "MESSAGE NUMBER", "length", "4"))
                .defineField(72, "n", Map.of("description", "MESSAGE NUMBER LAST", "length", "4"))
                .defineField(73, "n", Map.of("description", "DATE ACTION", "length", "6"))
                .defineField(74, "n", Map.of("description", "CREDITS NUMBER", "length", "10"))
                .defineField(75, "n", Map.of("description", "CREDITS REVERSAL NUMBER", "length", "10"))
                .defineField(76, "n", Map.of("description", "DEBITS NUMBER", "length", "10"))
                .defineField(77, "n", Map.of("description", "DEBITS REVERSAL NUMBER", "length", "10"))
                .defineField(78, "n", Map.of("description", "TRANSFER NUMBER", "length", "10"))
                .defineField(79, "n", Map.of("description", "TRANSFER REVERSAL NUMBER", "length", "10"))
                .defineField(80, "n", Map.of("description", "INQUIRIES NUMBER", "length", "10"))
                .defineField(81, "n", Map.of("description", "AUTHORIZATION NUMBER", "length", "10"))
                .defineField(82, "n", Map.of("description", "CREDITS, PROCESSING FEE AMOUNT", "length", "12"))
                .defineField(83, "n", Map.of("description", "CREDITS, TRANSACTION FEE AMOUNT", "length", "12"))
                .defineField(84, "n", Map.of("description", "DEBITS, PROCESSING FEE AMOUNT", "length", "12"))
                .defineField(85, "n", Map.of("description", "DEBITS, TRANSACTION FEE AMOUNT", "length", "12"))
                .defineField(86, "n", Map.of("description", "CREDITS, AMOUNT", "length", "16"))
                .defineField(87, "n", Map.of("description", "CREDITS, REVERSAL AMOUNT", "length", "16"))
                .defineField(88, "n", Map.of("description", "DEBITS, AMOUNT", "length", "16"))
                .defineField(89, "n", Map.of("description", "DEBITS, REVERSAL AMOUNT", "length", "16"))
                .defineField(90, "n", Map.of("description", "ORIGINAL DATA ELEMENTS", "length", "42"))
                .defineField(91, "s", Map.of("description", "FILE UPDATE CODE", "length", "1"))
                .defineField(92, "s", Map.of("description", "FILE SECURITY CODE", "length", "2"))
                .defineField(93, "s", Map.of("description", "RESPONSE INDICATOR", "length", "6"))
                .defineField(94, "s", Map.of("description", "SERVICE INDICATOR", "length", "7"))
                .defineField(95, "s", Map.of("description", "REPLACEMENT AMOUNTS", "length", "42"))
                .defineField(96, "b", Map.of("description", "MESSAGE SECURITY CODE", "length", "16"))
                .defineField(97, "n", Map.of("description", "AMOUNT, NET SETTLEMENT", "length", "17"))
                .defineField(98, "s", Map.of("description", "PAYEE", "length", "25"))
                .defineField(99, "n ..", Map.of("description", "SETTLEMENT INSTITUTION IDENT CODE", "max-length", "11"))
                .defineField(100, "n ..", Map.of("description", "RECEIVING INSTITUTION IDENT CODE", "max-length", "11"))
                .defineField(101, "ans ..", Map.of("description", "FILE NAME", "max-length", "17"))
                .defineField(102, "ans ..", Map.of("description", "ACCOUNT IDENTIFICATION 1", "max-length", "13"))
                .defineField(103, "ans ..", Map.of("description", "ACCOUNT IDENTIFICATION 2", "max-length", "10"))
                .defineField(104, "ans ...", Map.of("description", "TRANSACTION DESCRIPTION", "max-length", "100"))
                .defineField(105, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(106, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(107, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(108, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(109, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(110, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(111, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(112, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(113, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(114, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(115, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(116, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(117, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(118, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(119, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(120, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(121, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(122, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(123, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(124, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(125, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(126, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(127, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(128, "b", Map.of("description", "MAC 2", "length", "8"))
                .build());
    }
}
