package org.nucleus8583.core.config.spi;

import org.nucleus8583.core.MessageSerializer;
import org.nucleus8583.core.config.Configuration;
import org.nucleus8583.core.config.Configurer;
import org.nucleus8583.core.config.Order;

import java.util.Map;

@Order(Order.FIRST + 1)
public class Iso93AsciiSerializerConfig implements Configurer {

    @Override
    public void configure(Configuration config) {
        config.define("iso93ascii", MessageSerializer.custom(config)
                .defineField(0, "n", Map.of("length", "4", "alignment", "uright", "description", "MESSAGE TYPE INDICATOR"))
                .defineField(1, "bitmap", Map.of("description", "BIT MAP"))
                .defineField(2, "n ..", Map.of("max-length", "19", "description", "PRIMARY ACCOUNT NUMBER"))
                .defineField(3, "n", Map.of("length", "6", "alignment", "uright", "description", "PROCESSING CODE"))
                .defineField(4, "n", Map.of("length", "12", "alignment", "uright", "description", "AMOUNT, TRANSACTION"))
                .defineField(5, "n", Map.of("length", "12", "alignment", "uright", "description", "AMOUNT, RECONCILIATION"))
                .defineField(6, "n", Map.of("length", "12", "alignment", "uright", "description", "AMOUNT, CARDHOLDER BILLING"))
                .defineField(7, "n", Map.of("length", "10", "alignment", "uright", "description", "TRANSMISSION DATE AND TIME"))
                .defineField(8, "n", Map.of("length", "8", "alignment", "uright", "description", "AMOUNT, CARDHOLDER BILLING FEE"))
                .defineField(9, "n", Map.of("length", "8", "alignment", "uright", "description", "CONVERSION RATE, RECONCILIATION"))
                .defineField(10, "n", Map.of("length", "8", "alignment", "uright", "description", "CONVERSION RATE, CARDHOLDER BILLING"))
                .defineField(11, "n", Map.of("length", "6", "alignment", "uright", "description", "SYSTEM TRACE AUDIT NUMBER"))
                .defineField(12, "n", Map.of("length", "12", "alignment", "uright", "description", "DATE AND TIME, LOCAL TRANSACTION"))
                .defineField(13, "n", Map.of("length", "4", "alignment", "uright", "description", "DATE, EFFECTIVE"))
                .defineField(14, "n", Map.of("length", "4", "alignment", "uright", "description", "DATE, EXPIRATION"))
                .defineField(15, "n", Map.of("length", "6", "alignment", "uright", "description", "DATE, SETTLEMENT"))
                .defineField(16, "n", Map.of("length", "4", "alignment", "uright", "description", "DATE, CONVERSION"))
                .defineField(17, "n", Map.of("length", "4", "alignment", "uright", "description", "DATE, CAPTURE"))
                .defineField(18, "n", Map.of("length", "4", "alignment", "uright", "description", "MERCHANTS TYPE"))
                .defineField(19, "n", Map.of("length", "3", "alignment", "uright", "description", "ACQUIRING INSTITUTION COUNTRY CODE"))
                .defineField(20, "n", Map.of("length", "3", "alignment", "uright", "description", "PRIMARY ACCOUNT NUMBER COUNTRY CODE"))
                .defineField(21, "n", Map.of("length", "3", "alignment", "uright", "description", "FORWARDING INSTITUTION COUNTRY CODE"))
                .defineField(22, "ans", Map.of("length", "12", "alignment", "uleft", "description", "POINT OF SERVICE DATA CODE"))
                .defineField(23, "n", Map.of("length", "3", "alignment", "uright", "description", "CARD SEQUENCE NUMBER"))
                .defineField(24, "n", Map.of("length", "3", "alignment", "uright", "description", "FUNCTION CODE"))
                .defineField(25, "n", Map.of("length", "4", "alignment", "uright", "description", "MESSAGE REASON CODE"))
                .defineField(26, "n", Map.of("length", "4", "alignment", "uright", "description", "CARD ACCEPTOR BUSINESS CODE"))
                .defineField(27, "n", Map.of("length", "1", "alignment", "uright", "description", "APPROVAL CODE LEN"))
                .defineField(28, "n", Map.of("length", "6", "alignment", "uright", "description", "DATE, RECONCILIATION"))
                .defineField(29, "n", Map.of("length", "3", "alignment", "uright", "description", "RECONCILIATION INDICATOR"))
                .defineField(30, "n", Map.of("length", "24", "alignment", "uright", "description", "AMOUNTS, ORIGINAL"))
                .defineField(31, "ans ..", Map.of("max-length", "48", "description", "ACQUIRER REFERENCE DATA"))
                .defineField(32, "n ..", Map.of("max-length", "11", "description", "ACQUIRING INSTITUTION IDENT CODE"))
                .defineField(33, "n ..", Map.of("max-length", "11", "description", "FORWARDING INSTITUTION IDENT CODE"))
                .defineField(34, "ans ..", Map.of("max-length", "28", "description", "PAN EXTENDED"))
                .defineField(35, "ans ..", Map.of("max-length", "37", "description", "TRACK 2 DATA"))
                .defineField(36, "ans ...", Map.of("max-length", "104", "description", "TRACK 3 DATA"))
                .defineField(37, "ans", Map.of("length", "12", "alignment", "uleft", "description", "RETRIEVAL REFERENCE NUMBER"))
                .defineField(38, "ans", Map.of("length", "6", "alignment", "uleft", "description", "APPROVAL CODE"))
                .defineField(39, "n", Map.of("length", "3", "alignment", "uright", "description", "ACTION CODE"))
                .defineField(40, "n", Map.of("length", "3", "alignment", "uright", "description", "SERVICE CODE"))
                .defineField(41, "ans", Map.of("length", "8", "alignment", "uleft", "description", "CARD ACCEPTOR TERMINAL IDENTIFICACION"))
                .defineField(42, "ans", Map.of("length", "15", "alignment", "uleft", "description", "CARD ACCEPTOR IDENTIFICATION CODE"))
                .defineField(43, "ans ..", Map.of("description", "CARD ACCEPTOR NAME/LOCATION"))
                .defineField(44, "ans ..", Map.of("description", "ADITIONAL RESPONSE DATA"))
                .defineField(45, "ans ..", Map.of("max-length", "76", "description", "TRACK 1 DATA"))
                .defineField(46, "ans ...", Map.of("max-length", "204", "description", "AMOUNTS, FEE"))
                .defineField(47, "ans ...", Map.of("description", "ADITIONAL DATA - NATIONAL"))
                .defineField(48, "ans ...", Map.of("description", "ADITIONAL DATA - PRIVATE"))
                .defineField(49, "ans", Map.of("length", "3", "alignment", "uleft", "description", "CURRENCY CODE, TRANSACTION"))
                .defineField(50, "ans", Map.of("length", "3", "alignment", "uleft", "description", "CURRENCY CODE, RECONCILIATION"))
                .defineField(51, "ans", Map.of("length", "3", "alignment", "uleft", "description", "CURRENCY CODE, CARDHOLDER BILLING"))
                .defineField(52, "b", Map.of("length", "8", "description", "PIN DATA"))
                .defineField(53, "lb ..", Map.of("max-length", "48", "description", "SECURITY RELATED CONTROL INFORMATION"))
                .defineField(54, "ans ...", Map.of("max-length", "120", "description", "ADDITIONAL AMOUNTS"))
                .defineField(55, "lb ...", Map.of("max-length", "255", "description", "IC CARD SYSTEM RELATED DATA"))
                .defineField(56, "n ..", Map.of("max-length", "35", "description", "ORIGINAL DATA ELEMENTS"))
                .defineField(57, "n", Map.of("length", "3", "alignment", "uright", "description", "AUTHORIZATION LIFECYCLE CODE"))
                .defineField(58, "n ..", Map.of("max-length", "11", "description", "AUTHORIZING AGENT INSTITUTION ID CODE"))
                .defineField(59, "ans ...", Map.of("description", "TRANSPORT DATA"))
                .defineField(60, "ans ...", Map.of("description", "RESERVED FOR NATIONAL USE"))
                .defineField(61, "ans ...", Map.of("description", "RESERVED FOR NATIONAL USE"))
                .defineField(62, "ans ...", Map.of("description", "RESERVED PRIVATE"))
                .defineField(63, "ans ...", Map.of("description", "RESERVED PRIVATE"))
                .defineField(64, "b", Map.of("length", "8", "description", "MESSAGE AUTHENTICATION CODE FIELD"))
                .defineField(65, "bitmap", Map.of("description", "RESERVED FOR ISO USE"))
                .defineField(66, "ans ...", Map.of("max-length", "204", "description", "AMOUNTS, ORIGINAL FEES"))
                .defineField(67, "n", Map.of("length", "2", "alignment", "uright", "description", "EXTENDED PAYMENT DATA"))
                .defineField(68, "n", Map.of("length", "3", "alignment", "uright", "description", "RECEIVING INSTITUTION COUNTRY CODE"))
                .defineField(69, "n", Map.of("length", "3", "alignment", "uright", "description", "SETTLEMENT INSTITUTION COUNTRY CODE"))
                .defineField(70, "n", Map.of("length", "3", "alignment", "uright", "description", "AUTH AGENT INST COUNTRY CODE"))
                .defineField(71, "n", Map.of("length", "8", "alignment", "uright", "description", "MESSAGE NUMBER"))
                .defineField(72, "ans ...", Map.of("description", "DATA RECORD"))
                .defineField(73, "n", Map.of("length", "6", "alignment", "uright", "description", "DATE, ACTION"))
                .defineField(74, "n", Map.of("length", "10", "alignment", "uright", "description", "CREDITS, NUMBER"))
                .defineField(75, "n", Map.of("length", "10", "alignment", "uright", "description", "CREDITS, REVERSAL NUMBER"))
                .defineField(76, "n", Map.of("length", "10", "alignment", "uright", "description", "DEBITS NUMBER"))
                .defineField(77, "n", Map.of("length", "10", "alignment", "uright", "description", "DEBITS REVERSAL NUMBER"))
                .defineField(78, "n", Map.of("length", "10", "alignment", "uright", "description", "TRANSFER NUMBER"))
                .defineField(79, "n", Map.of("length", "10", "alignment", "uright", "description", "TRANSFER REVERSAL NUMBER"))
                .defineField(80, "n", Map.of("length", "10", "alignment", "uright", "description", "INQUIRIES NUMBER"))
                .defineField(81, "n", Map.of("length", "10", "alignment", "uright", "description", "AUTHORIZATIONS NUMBER"))
                .defineField(82, "n", Map.of("length", "10", "alignment", "uright", "description", "INQUIRIES REVERSAL NUMBER"))
                .defineField(83, "n", Map.of("length", "10", "alignment", "uright", "description", "PAYMENTS NUMBER"))
                .defineField(84, "n", Map.of("length", "10", "alignment", "uright", "description", "PAYMENTS REVERSAL NUMBER"))
                .defineField(85, "n", Map.of("length", "10", "alignment", "uright", "description", "FEE COLLECTIONS NUMBER"))
                .defineField(86, "n", Map.of("length", "16", "alignment", "uright", "description", "CREDITS, AMOUNT"))
                .defineField(87, "n", Map.of("length", "16", "alignment", "uright", "description", "CREDITS, REVERSAL AMOUNT"))
                .defineField(88, "n", Map.of("length", "16", "alignment", "uright", "description", "DEBITS, AMOUNT"))
                .defineField(89, "n", Map.of("length", "16", "alignment", "uright", "description", "DEBITS, REVERSAL AMOUNT"))
                .defineField(90, "n", Map.of("length", "10", "alignment", "uright", "description", "AUTHORIZATIONS REVERSAL NUMBER"))
                .defineField(91, "n", Map.of("length", "3", "alignment", "uright", "description", "TRX DEST INST ID COUNTRY CODE"))
                .defineField(92, "n", Map.of("length", "3", "alignment", "uright", "description", "TRX ORIG INST ID COUNTRY CODE"))
                .defineField(93, "n ..", Map.of("max-length", "11", "description", "TRX DEST INST ID CODE"))
                .defineField(94, "n ..", Map.of("max-length", "11", "description", "TRX ORIG INST ID CODE"))
                .defineField(95, "ans ..", Map.of("description", "CARD ISSUER REFERENCE DATA"))
                .defineField(96, "lb ...", Map.of("description", "KEY MANAGEMENT DATA"))
                .defineField(97, "amount", Map.of("length", "17", "alignment", "uright", "description", "AMOUNT, NET RECONCILIATION"))
                .defineField(98, "ans", Map.of("length", "25", "alignment", "uleft", "description", "PAYEE"))
                .defineField(99, "ans ..", Map.of("max-length", "11", "description", "SETTLEMENT INSTITUTION IDENT CODE"))
                .defineField(100, "n ..", Map.of("max-length", "11", "description", "RECEIVING INSTITUTION IDENT CODE"))
                .defineField(101, "ans ..", Map.of("max-length", "17", "description", "FILE NAME"))
                .defineField(102, "ans ..", Map.of("max-length", "28", "description", "ACCOUNT IDENTIFICATION 1"))
                .defineField(103, "ans ..", Map.of("max-length", "28", "description", "ACCOUNT IDENTIFICATION 2"))
                .defineField(104, "ans ...", Map.of("max-length", "100", "description", "TRANSACTION DESCRIPTION"))
                .defineField(105, "n", Map.of("length", "16", "alignment", "uright", "description", "CREDITS, CHARGEBACK AMOUNT"))
                .defineField(106, "n", Map.of("length", "16", "alignment", "uright", "description", "DEBITS, CHARGEBACK AMOUNT"))
                .defineField(107, "n", Map.of("length", "10", "alignment", "uright", "description", "CREDITS, CHARGEBACK NUMBER"))
                .defineField(108, "n", Map.of("length", "10", "alignment", "uright", "description", "DEBITS, CHARGEBACK NUMBER"))
                .defineField(109, "ans ..", Map.of("max-length", "84", "description", "CREDITS, FEE AMOUNTS"))
                .defineField(110, "ans ..", Map.of("max-length", "84", "description", "DEBITS, FEE AMOUNTS"))
                .defineField(111, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(112, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(113, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(114, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(115, "ans ...", Map.of("description", "RESERVED ISO USE"))
                .defineField(116, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(117, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(118, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(119, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(120, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(121, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(122, "ans ...", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(123, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(124, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(125, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(126, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(127, "ans ...", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(128, "b", Map.of("length", "8", "description", "MAC FIELD"))
                .build());
    }
}
