package org.nucleus8583.core.config.spi;

import org.nucleus8583.core.MessageSerializer;
import org.nucleus8583.core.config.Configuration;
import org.nucleus8583.core.config.Configurer;
import org.nucleus8583.core.config.Order;

import java.util.Map;

@Order(Order.FIRST + 1)
public class Iso93BinarySerializerConfig implements Configurer {

    @Override
    public void configure(Configuration config) {
        config.define("iso93binary", MessageSerializer.custom(config)
                .defineField(0, "bcd", Map.of("length", "4", "alignment", "uright", "description", "MESSAGE TYPE INDICATOR"))
                .defineField(1, "lbitmap", Map.of("description", "BIT MAP"))
                .defineField(2, "bcd .. bcd", Map.of("alignment", "uleft", "max-length", "19", "description", "PRIMARY ACCOUNT NUMBER"))
                .defineField(3, "bcd", Map.of("length", "6", "alignment", "none", "description", "PROCESSING CODE"))
                .defineField(4, "bcd", Map.of("length", "12", "alignment", "none", "description", "AMOUNT, TRANSACTION"))
                .defineField(5, "bcd", Map.of("length", "12", "alignment", "none", "description", "AMOUNT, SETTLEMENT"))
                .defineField(6, "bcd", Map.of("length", "12", "alignment", "none", "description", "AMOUNT, CARDHOLDER BILLING"))
                .defineField(7, "bcd", Map.of("length", "10", "alignment", "none", "description", "TRANSMISSION DATE AND TIME"))
                .defineField(8, "bcd", Map.of("length", "8", "alignment", "none", "description", "AMOUNT, CARDHOLDER BILLING FEE"))
                .defineField(9, "bcd", Map.of("length", "8", "alignment", "none", "description", "CONVERSION RATE, SETTLEMENT"))
                .defineField(10, "bcd", Map.of("length", "8", "alignment", "none", "description", "CONVERSION RATE, CARDHOLDER BILLING"))
                .defineField(11, "bcd", Map.of("length", "6", "alignment", "none", "description", "SYSTEM TRACE AUDIT NUMBER"))
                .defineField(12, "bcd", Map.of("length", "12", "alignment", "none", "description", "DATE AND TIME, LOCAL TRANSACTION"))
                .defineField(13, "bcd", Map.of("length", "4", "alignment", "none", "description", "DATE, EFFECTIVE"))
                .defineField(14, "bcd", Map.of("length", "4", "alignment", "none", "description", "DATE, EXPIRATION"))
                .defineField(15, "bcd", Map.of("length", "6", "alignment", "none", "description", "DATE, SETTLEMENT"))
                .defineField(16, "bcd", Map.of("length", "4", "alignment", "none", "description", "DATE, CONVERSION"))
                .defineField(17, "bcd", Map.of("length", "4", "alignment", "none", "description", "DATE, CAPTURE"))
                .defineField(18, "bcd", Map.of("length", "4", "alignment", "none", "description", "MERCHANTS TYPE"))
                .defineField(19, "bcd", Map.of("length", "3", "alignment", "none", "description", "ACQUIRING INSTITUTION COUNTRY CODE"))
                .defineField(20, "bcd", Map.of("length", "3", "alignment", "none", "description", "PAN EXTENDED COUNTRY CODE"))
                .defineField(21, "bcd", Map.of("length", "3", "alignment", "none", "description", "FORWARDING INSTITUTION COUNTRY CODE"))
                .defineField(22, "ans", Map.of("length", "12", "alignment", "uleft", "description", "POINT OF SERVICE DATA CODE"))
                .defineField(23, "bcd", Map.of("length", "3", "alignment", "none", "description", "CARD SEQUENCE NUMBER"))
                .defineField(24, "bcd", Map.of("length", "3", "alignment", "none", "description", "FUNCTION CODE"))
                .defineField(25, "bcd", Map.of("length", "4", "alignment", "none", "description", "MESSAGE REASON CODE"))
                .defineField(26, "bcd", Map.of("length", "4", "alignment", "none", "description", "CARD ACCEPTOR BUSINESS CODE"))
                .defineField(27, "bcd", Map.of("length", "1", "alignment", "none", "description", "AUTHORIZATION IDENTIFICATION RESP LEN"))
                .defineField(28, "bcd", Map.of("length", "6", "alignment", "none", "description", "AMOUNT, TRANSACTION FEE"))
                .defineField(29, "bcd", Map.of("length", "3", "alignment", "none", "description", "AMOUNT, SETTLEMENT FEE"))
                .defineField(30, "bcd", Map.of("length", "24", "alignment", "none", "description", "AMOUNTS, ORIGINAL"))
                .defineField(31, "an .. bcd", Map.of("max-length", "48", "description", "ACQUIRER REFERENCE DATA"))
                .defineField(32, "bcd .. bcd", Map.of("alignment", "uleft", "max-length", "11", "description", "ACQUIRING INSTITUTION IDENT CODE"))
                .defineField(33, "bcd .. bcd", Map.of("alignment", "uleft", "max-length", "11", "description", "FORWARDING INSTITUTION IDENT CODE"))
                .defineField(34, "an .. bcd", Map.of("max-length", "28", "description", "PAN EXTENDED"))
                .defineField(35, "an .. bcd", Map.of("max-length", "37", "description", "TRACK 2 DATA"))
                .defineField(36, "an ... bcd", Map.of("max-length", "104", "description", "TRACK 3 DATA"))
                .defineField(37, "an", Map.of("length", "12", "alignment", "uleft", "description", "RETRIEVAL REFERENCE NUMBER"))
                .defineField(38, "an", Map.of("length", "6", "alignment", "uleft", "description", "AUTHORIZATION IDENTIFICATION RESPONSE"))
                .defineField(39, "bcd", Map.of("length", "3", "alignment", "none", "description", "RESPONSE CODE"))
                .defineField(40, "bcd", Map.of("length", "3", "alignment", "none", "description", "SERVICE RESTRICTION CODE"))
                .defineField(41, "an", Map.of("length", "8", "alignment", "uleft", "description", "CARD ACCEPTOR TERMINAL IDENTIFICACION"))
                .defineField(42, "an", Map.of("length", "15", "alignment", "uleft", "description", "CARD ACCEPTOR IDENTIFICATION CODE"))
                .defineField(43, "an .. bcd", Map.of("description", "CARD ACCEPTOR NAME/LOCATION"))
                .defineField(44, "an .. bcd", Map.of("max-length", "25", "description", "ADDITIONAL RESPONSE DATA"))
                .defineField(45, "an .. bcd", Map.of("max-length", "76", "description", "TRACK 1 DATA"))
                .defineField(46, "an ... bcd", Map.of("description", "ADITIONAL DATA - ISO"))
                .defineField(47, "an ... bcd", Map.of("description", "ADITIONAL DATA - NATIONAL"))
                .defineField(48, "an ... bcd", Map.of("description", "ADITIONAL DATA - PRIVATE"))
                .defineField(49, "an", Map.of("length", "3", "alignment", "uleft", "description", "CURRENCY CODE, TRANSACTION"))
                .defineField(50, "an", Map.of("length", "3", "alignment", "uleft", "description", "CURRENCY CODE, SETTLEMENT"))
                .defineField(51, "an", Map.of("length", "3", "alignment", "uleft", "description", "CURRENCY CODE, CARDHOLDER BILLING"))
                .defineField(52, "lb", Map.of("length", "8", "alignment", "none", "description", "PIN DATA"))
                .defineField(53, "lb .. bcd", Map.of("max-length", "48", "description", "SECURITY RELATED CONTROL INFORMATION"))
                .defineField(54, "an ... bcd", Map.of("max-length", "120", "description", "ADDITIONAL AMOUNTS"))
                .defineField(55, "lb ... bcd", Map.of("description", "IC CARD SYSTEM RELATED DATA"))
                .defineField(56, "bcd .. bcd", Map.of("max-length", "35", "description", "ORIGINAL DATA ELEMENTS"))
                .defineField(57, "bcd", Map.of("length", "3", "alignment", "none", "description", "RESERVED NATIONAL"))
                .defineField(58, "bcd .. bcd", Map.of("alignment", "uleft", "max-length", "11", "description", "RESERVED NATIONAL"))
                .defineField(59, "an ... bcd", Map.of("description", "RESERVED NATIONAL"))
                .defineField(60, "an ... bcd", Map.of("description", "RESERVED PRIVATE"))
                .defineField(61, "an ... bcd", Map.of("description", "RESERVED PRIVATE"))
                .defineField(62, "an ... bcd", Map.of("description", "RESERVED PRIVATE"))
                .defineField(63, "an ... bcd", Map.of("description", "RESERVED PRIVATE"))
                .defineField(64, "lb", Map.of("length", "8", "description", "MESSAGE AUTHENTICATION CODE FIELD"))
                .defineField(65, "lbitmap", Map.of("description", "BITMAP, EXTENDED"))
                .defineField(66, "an ... bcd", Map.of("max-length", "204", "description", "SETTLEMENT CODE"))
                .defineField(67, "bcd", Map.of("length", "2", "alignment", "none", "description", "EXTENDED PAYMENT CODE"))
                .defineField(68, "bcd", Map.of("length", "3", "alignment", "none", "description", "RECEIVING INSTITUTION COUNTRY CODE"))
                .defineField(69, "bcd", Map.of("length", "3", "alignment", "none", "description", "SETTLEMENT INSTITUTION COUNTRY CODE"))
                .defineField(70, "bcd", Map.of("length", "3", "alignment", "none", "description", "NETWORK MANAGEMENT INFORMATION CODE"))
                .defineField(71, "bcd", Map.of("length", "8", "alignment", "none", "description", "MESSAGE NUMBER"))
                .defineField(72, "an ... bcd", Map.of("description", "MESSAGE NUMBER LAST"))
                .defineField(73, "bcd", Map.of("length", "6", "alignment", "none", "description", "DATE ACTION"))
                .defineField(74, "bcd", Map.of("length", "10", "alignment", "none", "description", "CREDITS NUMBER"))
                .defineField(75, "bcd", Map.of("length", "10", "alignment", "none", "description", "CREDITS REVERSAL NUMBER"))
                .defineField(76, "bcd", Map.of("length", "10", "alignment", "none", "description", "DEBITS NUMBER"))
                .defineField(77, "bcd", Map.of("length", "10", "alignment", "none", "description", "DEBITS REVERSAL NUMBER"))
                .defineField(78, "bcd", Map.of("length", "10", "alignment", "none", "description", "TRANSFER NUMBER"))
                .defineField(79, "bcd", Map.of("length", "10", "alignment", "none", "description", "TRANSFER REVERSAL NUMBER"))
                .defineField(80, "bcd", Map.of("length", "10", "alignment", "none", "description", "INQUIRIES NUMBER"))
                .defineField(81, "bcd", Map.of("length", "10", "alignment", "none", "description", "AUTHORIZATION NUMBER"))
                .defineField(82, "bcd", Map.of("length", "10", "alignment", "none", "description", "CREDITS, PROCESSING FEE AMOUNT"))
                .defineField(83, "bcd", Map.of("length", "10", "alignment", "none", "description", "CREDITS, TRANSACTION FEE AMOUNT"))
                .defineField(84, "bcd", Map.of("length", "10", "alignment", "none", "description", "DEBITS, PROCESSING FEE AMOUNT"))
                .defineField(85, "bcd", Map.of("length", "10", "alignment", "none", "description", "DEBITS, TRANSACTION FEE AMOUNT"))
                .defineField(86, "bcd", Map.of("length", "16", "alignment", "none", "description", "CREDITS, AMOUNT"))
                .defineField(87, "bcd", Map.of("length", "16", "alignment", "none", "description", "CREDITS, REVERSAL AMOUNT"))
                .defineField(88, "bcd", Map.of("length", "16", "alignment", "none", "description", "DEBITS, AMOUNT"))
                .defineField(89, "bcd", Map.of("length", "16", "alignment", "none", "description", "DEBITS, REVERSAL AMOUNT"))
                .defineField(90, "bcd", Map.of("length", "10", "alignment", "none", "description", "ORIGINAL DATA ELEMENTS"))
                .defineField(91, "bcd", Map.of("length", "3", "alignment", "none", "description", "FILE UPDATE CODE"))
                .defineField(92, "bcd", Map.of("length", "3", "alignment", "none", "description", "FILE SECURITY CODE"))
                .defineField(93, "bcd .. bcd", Map.of("alignment", "uleft", "max-length", "11", "description", "RESPONSE INDICATOR"))
                .defineField(94, "bcd .. bcd", Map.of("alignment", "uleft", "max-length", "11", "description", "SERVICE INDICATOR"))
                .defineField(95, "an .. bcd", Map.of("description", "REPLACEMENT AMOUNTS"))
                .defineField(96, "lb ... bcd", Map.of("description", "MESSAGE SECURITY CODE"))
                .defineField(97, "bcd amount", Map.of("length", "17", "alignment", "uright", "description", "AMOUNT, NET SETTLEMENT"))
                .defineField(98, "an", Map.of("length", "25", "alignment", "none", "description", "PAYEE"))
                .defineField(99, "an .. bcd", Map.of("max-length", "11", "description", "SETTLEMENT INSTITUTION IDENT CODE"))
                .defineField(100, "bcd .. bcd", Map.of("alignment", "uleft", "max-length", "11", "description", "RECEIVING INSTITUTION IDENT CODE"))
                .defineField(101, "an .. bcd", Map.of("max-length", "17", "description", "FILE NAME"))
                .defineField(102, "an .. bcd", Map.of("max-length", "28", "description", "ACCOUNT IDENTIFICATION 1"))
                .defineField(103, "an .. bcd", Map.of("max-length", "28", "description", "ACCOUNT IDENTIFICATION 2"))
                .defineField(104, "an ... bcd", Map.of("max-length", "100", "description", "TRANSACTION DESCRIPTION"))
                .defineField(105, "bcd", Map.of("length", "16", "alignment", "none", "description", "RESERVED ISO USE"))
                .defineField(106, "bcd", Map.of("length", "16", "alignment", "none", "description", "RESERVED ISO USE"))
                .defineField(107, "bcd", Map.of("length", "10", "alignment", "none", "description", "RESERVED ISO USE"))
                .defineField(108, "bcd", Map.of("length", "10", "alignment", "none", "description", "RESERVED ISO USE"))
                .defineField(109, "an .. bcd", Map.of("max-length", "84", "description", "RESERVED ISO USE"))
                .defineField(110, "an .. bcd", Map.of("max-length", "84", "description", "RESERVED ISO USE"))
                .defineField(111, "an ... bcd", Map.of("description", "RESERVED ISO USE"))
                .defineField(112, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(113, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(114, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(115, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(116, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(117, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(118, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(119, "an ... bcd", Map.of("description", "RESERVED NATIONAL USE"))
                .defineField(120, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(121, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(122, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(123, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(124, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(125, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(126, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(127, "an ... bcd", Map.of("description", "RESERVED PRIVATE USE"))
                .defineField(128, "lb", Map.of("length", "8", "alignment", "none", "description", "MAC 2"))
                .build());
    }
}
